### ISSUE TITLE
Unable to download package nvidia-container-toolkit on Bionic

### ISSUE THREAD

**Issue by knickels** [NVIDIA/nvidia-docker#1048]
Fixed, sorry about that, I updated the docs a bit too early.

_Originally posted by @RenaudWasTaken in https://github.com/NVIDIA/nvidia-docker/issues/1022#issuecomment-514063480_

I'm experiencing the same issue with a fresh install of ubuntu18.04, following the current README.

**Comment by ylyhlh** [comment]
Same issue here, from ubuntu18.04, CUDA 10.1. Following the README. Cannot find nvidia-container-toolkit in the package

**Comment by taemon1337** [comment]
I'm seeing same thing on Centos7, must have happened very recently as it worked a day or two ago.

**Comment by kwskii** [comment]
Same thing for ubuntu18.04, CUDA 8.0. Following the Readme. Cannot find nvidia-container-toolkit in the package

**Comment by acowlikeobject** [comment]
Can't install `nvidia-container-runtime` on ubuntu18.04.  Maybe related (following the README installation steps, which were working fine till about 24 hours ago):

```
$ sudo apt-get install -y nvidia-docker2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: nvidia-container-runtime (>= 3.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Ethyling** [comment]
Hey, we are working on fixing the issue. I will come back to you once the problem is resolved. Thank you for your report.

**Comment by ffahmed** [comment]
we have the same problem

**Comment by Ethyling** [comment]
Hey, this should be fixed now. Sorry about that. Thank you again for the report

**Comment by taemon1337** [comment]
I am still unable to install nvidia-container-toolkit on CentOS7, did the centos7 repo get fixed?

**Comment by Ethyling** [comment]
@taemon1337 I can't reproduce the bug with a fresh CentOS7 instance. Maybe you need to update some cache?

**Comment by taemon1337** [comment]
Yeah I was thinking that, removed /var/cache/yum/x86_64/7/*nvidia* and yum clean all but still nothing.  Sounds like the issue is my system though :(
