### ISSUE TITLE
Support Jetson Xavier NX 

### ISSUE THREAD

**Issue by copiltembel** [NVIDIA/nvidia-docker#1353]
### 1. Issue or feature description

Are there any plans to support also the Jetson Xavier NX device?

**Comment by paldana-ISI** [comment]
Just want to bump this issue as I have a similar sentiment though for **Jetson AGX Xavier**.

**Comment by reubenbijl** [comment]
Hey, this is working well for me on a Xavier NX, initially I had some issues and so I tried starting with the JetPack image again and all working fine since.

**Comment by paldana-ISI** [comment]
> Hey, this is working well for me on a Xavier NX, initially I had some issues and so I tried starting with the JetPack image again and all working fine since.

@reubenbijl what kind of issues were you having? At first, I noticed that the nvidia-docker2 came pre-installed with the Jetpack 4.2 so I did the "hello-world" shell script and it went fine. But when I'm trying to create a container using **nvidia/cuda**, I'm getting the error below:

`nvidia@x02:~$ nvidia-docker run --rm -ti nvidia/cuda nvcc --version
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.`

For reference, I also posted my issue on this post where people have a similar problem but no solutions yet: https://github.com/NVIDIA/nvidia-docker/issues/1203#issuecomment-670640220

**Comment by reubenbijl** [comment]
Yes, very similar error.
"docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown."

I didn't note everything I did on my first install compared to the second, but one major difference was setting up via GNOME and configuring RDP, whereas the second configuration I used the serial interface to configure the device, and only used it via ssh.

**Comment by paldana-ISI** [comment]
Interesting.. I'm accessing it via SSH as well, yet I'm having issues. May I know what's the Jetpack version of your working environment?

**Comment by reubenbijl** [comment]
cat /etc/nv_tegra_release

# R32 (release), REVISION: 4.3, GCID: 21589087, BOARD: t186ref, EABI:
aarch64, DATE: Fri Jun 26 04:34:27 UTC 2020

**Comment by reubenbijl** [comment]
apt-cache show nvidia-jetpack

Package: nvidia-jetpack

Version: 4.4-b186

Architecture: arm64

**Comment by paldana-ISI** [comment]
Thanks! Was your first install also using Jetpack 4.4?

**Comment by reubenbijl** [comment]
Yes, same image.

**Comment by adfayed** [comment]
> > Hey, this is working well for me on a Xavier NX, initially I had some issues and so I tried starting with the JetPack image again and all working fine since.
> 
> @reubenbijl what kind of issues were you having? At first, I noticed that the nvidia-docker2 came pre-installed with the Jetpack 4.2 so I did the "hello-world" shell script and it went fine. But when I'm trying to create a container using **nvidia/cuda**, I'm getting the error below:
> 
> **nvidia@x02:~$ nvidia-docker run --rm -ti nvidia/cuda nvcc --version**
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.`
> 
> For reference, I also posted my issue on this post where people have a similar problem but no solutions yet: [#1203 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1203#issuecomment-670640220)

I am having the same issue with my Jetson AGX Xavier 32Gb, @paldana-ISI any luck on following the second fresh install mentioned? I am wondering if I should go ahead and try it.

**Comment by pmundt** [comment]
This particular error is often encountered when one is trying to run containers for a different architecture. Looking at the `nvidia/cuda` repo on docker hub confirms this - there are only amd64 images published. You may be able to build an arm64 version directly on the Xavier board reusing the same Dockerfile though.

**Comment by raffraffraff** [comment]
FYI, there are ARM images, but they're not under a different _tag_, they have a different _name_:

```
sudo nvidia-docker run --net=host --rm nvidia/cuda-arm64:11.0-base nvidia-smi
```

Unfortunately, it probably still won't work. I'm using a Jetson Xavier AGX, running JetPack 4.5.1. No dice.

**Comment by wulongwei** [comment]
The problem has been solved. Share it with you：
`sudo apt install libnvidia-container-tools libnvidia-container0:arm64 nvidia-container-runtime nvidia-container-toolkit nvidia-docker2`

**Comment by elezar** [comment]
The newer versions of the NVIDIA Container Toolkit offer improved Tegra support.

If problems persist, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit
