### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by zhenyulin** [NVIDIA/nvidia-docker#319]
running on an AWS EC2 g2.2xlarge instance with Ubuntu 16.04 with all updates installed

gpu drivers installed following instructions in the [doc](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2) without the docker-machine part

driver versions are as following

> ii  nvidia-375                       375.39-0ubuntu0-gpu16.04.2        amd64        NVIDIA binary driver - version 375.39
ii  nvidia-375-dev                   375.39-0ubuntu0-gpu16.04.2        amd64        NVIDIA binary Xorg driver development files
ii  nvidia-cuda-dev                  7.5.18-0ubuntu1                   amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                  7.5.18-0ubuntu1                   all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                  7.5.18-0ubuntu1                   amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit              7.5.18-0ubuntu1                   amd64        NVIDIA CUDA development toolkit
ii  nvidia-docker                    1.0.0-1                           amd64        NVIDIA Docker container tools
ii  nvidia-modprobe                  375.26-0ubuntu1                   amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-dev:amd64          7.5.18-0ubuntu1                   amd64        NVIDIA OpenCL development files
ii  nvidia-opencl-icd-375            375.39-0ubuntu0-gpu16.04.2        amd64        NVIDIA OpenCL ICD
ii  nvidia-profiler                  7.5.18-0ubuntu1                   amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                  378.09-0ubuntu0-gpu16.04.1        amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-visual-profiler           7.5.18-0ubuntu1                   amd64        NVIDIA Visual Profiler for CUDA and OpenCL

tried solutions in #106 , but doesn't help

**Comment by flx42** [comment]
Did you really follow the instructions for installing the driver? NVIDIA doesn't package `375.39`, only `375.26`. You have both versions installed in your packages, so that's weird.
What's the output of `apt-cache policy nvidia-375`?
You do have `nvidia-modprobe` installed actually, so I'm not sure yet why it fails.

**Comment by zhenyulin** [comment]
just restarted a new instance and went over the routine again, still got the same error

diagnose information as following

`lspci | grep -i vga`

> 00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:03.0 VGA compatible controller: NVIDIA Corporation GK104GL [GRID K520] (rev a1)

`dpkg -l | grep -i nvidia`

> ii  libcuda1-375                     375.26-0ubuntu1                   amd64        NVIDIA CUDA runtime library
ii  nvidia-375                       375.26-0ubuntu1                   amd64        NVIDIA binary driver - version 375.26
ii  nvidia-375-dev                   375.26-0ubuntu1                   amd64        NVIDIA binary Xorg driver development files
ii  nvidia-docker                    1.0.0-1                           amd64        NVIDIA Docker container tools
ii  nvidia-modprobe                  375.26-0ubuntu1                   amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-icd-375            375.26-0ubuntu1                   amd64        NVIDIA OpenCL ICD
ii  nvidia-settings                  375.26-0ubuntu1                   amd64        Tool for configuring the NVIDIA graphics driver

**Comment by zhenyulin** [comment]
launched a new gpu instance with Ubuntu 14.04 and came across the same issue

**Comment by zhenyulin** [comment]
Further

run `service nvidia-docker status`

get
> ● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2017-02-23 15:28:25 UTC; 34s ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 15154 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 15133 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 15124 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
  Process: 15123 ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR (code=exited, status=1/FAILURE)
 Main PID: 15123 (code=exited, status=1/FAILURE)

Feb 23 15:28:24 ip-172-31-39-239 systemd[1]: nvidia-docker.service: Unit entered failed state.
Feb 23 15:28:24 ip-172-31-39-239 systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
Feb 23 15:28:25 ip-172-31-39-239 systemd[1]: nvidia-docker.service: Service hold-off time over, scheduling restart.
Feb 23 15:28:25 ip-172-31-39-239 systemd[1]: Stopped NVIDIA Docker plugin.
Feb 23 15:28:25 ip-172-31-39-239 systemd[1]: nvidia-docker.service: Start request repeated too quickly.
Feb 23 15:28:25 ip-172-31-39-239 systemd[1]: Failed to start NVIDIA Docker plugin.

**Comment by zhenyulin** [comment]
solved the problem for me by downgrade the driver to 367.48

following the instruction [here](http://www.cs.stevens.edu/~kbatsos/awscudasetup.html)

**Comment by flx42** [comment]
Thanks for sharing your results, I will take a look at 375 on AWS.

**Comment by flx42** [comment]
There is indeed an issue with driver 375 **on g2 instances**. I will upgrade the tutorial to use p2 instances instead. If you need to use g2 instance, you should indeed stick to driver 367 for now.

**Comment by zhenyulin** [comment]
I just started a p2 instance with the AMI created from the previous g2 instance, was wondering if the driver version will influence computing efficiency?

**Comment by azu1129** [comment]
Same here. AWS EC2 g2.2xlarge with Ubntu14.

I guess CUDA installer make graphic driver update to nvidia-375 (is mismatch with K520).

my process is  following.( preparation like disable nouveau is done)

- sudo apt-get purge nvidia*
- sudo apt-get purge cuda*
- sudo sh NVIDIA-Linux-x86_64-352.79.run -a --disable-nouveau
- sudo reboot
- sudo dpkg -l | grep nvidia (no message displayed)
- sudo modprobe nvidia (no message displayed)
- sudo apt-get install cuda-7-5

following message shown in cuda-7-5 installation.
> Loading new nvidia-375-375.26 DKMS files...
> ...
> 
> nvidia_375:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/3.13.0-110-generic/updates/dkms/
> ...
> DKMS: install completed.
> Setting up nvidia-375-dev (375.26-0ubuntu1) ...
> Setting up libcuda1-375 (375.26-0ubuntu1) ...
> Setting up nvidia-modprobe (375.26-0ubuntu1) ...
> Setting up nvidia-settings (375.26-0ubuntu1) ...
> Setting up nvidia-opencl-icd-375 (375.26-0ubuntu1) ...
> Setting up cuda-drivers (375.26-1) ...
> Setting up cuda-runtime-7-5 (7.5-18) ...
> Setting up cuda-7-5 (7.5-18) ...

after cuda install, dmesg shows, 

> [ 568.286327] NVRM: The NVIDIA GRID K520 GPU installed in this system is
> [ 568.286327] NVRM: supported through the NVIDIA 367.xx Legacy drivers. Please
> [ 568.286327] NVRM: visit http://www.nvidia.com/object/unix.html for more
> [ 568.286327] NVRM: information. The 375.26 NVIDIA driver will ignore
> [ 568.286327] NVRM: this GPU. Continuing probe...

$ nvidia-smi

> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

$ sudo modprobe nvidia

> modprobe: ERROR: could not insert 'nvidia_375': No such device

**Comment by flx42** [comment]
@azu1129 doing `sudo apt-get install -y nvidia-367` might be enough.

**Comment by azu1129** [comment]
Thank you flx42, It works!

$ sudo modprobe nvidia (no message) 

$ sudo dpkg -l | grep nvidia
> ii  nvidia-367                                367.57-0ubuntu0.14.04.1                             amd64        NVIDIA binary driver - version 367.57
> rc  nvidia-375                                375.26-0ubuntu1                                     amd64        NVIDIA binary driver - version 375.26
> ii  nvidia-modprobe                           375.26-0ubuntu1                                     amd64        Load the NVIDIA kernel driver and create device files
> ii  nvidia-opencl-icd-367                     367.57-0ubuntu0.14.04.1                             amd64        NVIDIA OpenCL ICD
> rc  nvidia-opencl-icd-375                     375.26-0ubuntu1                                     amd64        NVIDIA OpenCL ICD
> ii  nvidia-prime                              0.6.2.1                                             amd64        Tools to enable NVIDIA's Prime
> ii  nvidia-settings                           375.26-0ubuntu1                                     amd64        Tool for configuring the NVIDIA graphics driver

cd /usr/local/cuda/samples/1_Utilities/deviceQuery
sudo make
./deviceQuery

> ...
> deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = GRID K520
> Result = PASS

**Comment by flx42** [comment]
And with `nvidia-367`, you can still use CUDA 8.0.

**Comment by azu1129** [comment]
Since the install problem has been solved, I will try CUDA 8.0 :)

**Comment by siddharthm83** [comment]
@azu1129 @flx42 , still having problems with cuda 8 and 367 driver on AWS g2.2xlarge. Did it work for you when you updated?

**Comment by arnaudmiribel** [comment]
Any solution now for g2 instances @flx42 ? 
I run into the exact same issues as @zhenyulin

**Comment by flx42** [comment]
@arnaudmiribel Which driver do you have? The latest versions of driver 375 re-added support for g2 instances.

**Comment by arnaudmiribel** [comment]
I'm sorry. Version is 381.22. Here's the info :  

Calling `$nvidia-smi` returns

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   46C    P8    18W / 125W |    875MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3799    C   /home/ubuntu/anaconda3/bin/python              864MiB |
+-----------------------------------------------------------------------------+
```

**Comment by nabobnagari** [comment]
GPU #0: GRID K520 (8 SMX), using 40 blocks of 8 threads

 Means  ?

While comparing with CPU It shows 312h/s while for GPU only 124h/s, Please throw some light what am i missing  ?

**Comment by flx42** [comment]
@arnaudmiribel it's working fine for you

@nabobnagari I don't understand your question.

**Comment by nabobnagari** [comment]
For GPU  mining In g2 2xlarger, gettting 124h/s

for CPU mining on the same g2 2xlarge geting 300h/s

Do we still need to tweek GPU Miner ?

**Comment by flx42** [comment]
@nabobnagari I can't comment on performance of an application I know nothing about.

**Comment by flx42** [comment]
Locking this issue since it was hijacked for a different question.
