### ISSUE TITLE
Problem with repositories for Ubuntu 16.04

### ISSUE THREAD

**Issue by sb5518** [NVIDIA/nvidia-docker#571]
When trying to create a docker image with nvidia-docker build the following issue arises:

W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release' is not signed.
W: GPG error: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: The repository 'http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release' is not signed.
E: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Failed to fetch http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

This occurred after compiling an image that was working perfectly until two days ago, and in different environments.

**Comment by flx42** [comment]
Can you try again @sb5518? We released CUDA 9.1 recently on this repository, and sometimes we hit issues with our CDN when a new release happens.

**Comment by sb5518** [comment]
Unfortunately I just tried again in two different environments and the issue persists. On one of the environments it shows the previous issue and in the other one:

E: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by flx42** [comment]
Which country are you in? It might be a CDN issue since I'm not seeing that from the US.

**Comment by flx42** [comment]
Ping @sb5518

**Comment by flx42** [comment]
No update, closing. If it persists, try contacting a local NVIDIA representative, as it might be a CDN issue related to your region, I can't help you any further.

**Comment by YankeeMarco** [comment]
nvidia technical staff

**Comment by Pingmin** [comment]
I got this too on Ubuntu 16.04 by "apt-get update" :

Error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg  
  The following signatures were invalid： BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>

=== Chinese ===

错误: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg  
  下列签名无效： BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
......
W: 校验数字签名时出错。此仓库未被更新，所以仍然使用此前的索引文件。GPG 错误：http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: 下列签名无效： BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: 无法下载 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Release.gpg  下列签名无效： BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

**Comment by flx42** [comment]
@Pingmin can you try again in a few hours? If it persists, I will ask for a CDN cache flush.

**Comment by vincentbissonnette** [comment]
I also have the exact same issue here, on nvidia/cuda:8.0 and 9.0 docker images for Ubuntu 16.04. 
I am located in France.

**Comment by jillesvangurp** [comment]
Same here:

```
    amazon-ebs: TASK [esrepo : Add curator Repository] *****************************************
    amazon-ebs: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:Failed to fetch http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages.gz  Hash Sum mismatch, E:Some index files failed to download. They have been ignored, or old ones used instead.
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_47Bfo6/ansible_module_apt_repository.py\", line 556, in <module>\n    main()\n  File \"/tmp/ansible_47Bfo6/ansible_module_apt_repository.py\", line 544, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:Failed to fetch http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages.gz  Hash Sum mismatch, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
    amazon-ebs: 	to retry, use: --limit @/Users/jillesvangurp/git/inbot/das-boot/packer/dockercompose_node.retry
```

This is happening as part of our packer ami build. We're building using a very recent base image (ami-4d46d534) of xenial in eu-west-1.

If there is a workaround, that would be great. This is currently blocking me shipping some updates to our amis.

**Comment by flx42** [comment]
@vincentbissonnette Use `nvidia/cuda:8.0-devel` or `nvidia/cuda:9.0-devel`

**Comment by vincentbissonnette** [comment]
I am indeed using the `devel` images in both cases. Sorry that was unclear.

**Comment by flx42** [comment]
@vincentbissonnette can you post the log?

**Comment by vincentbissonnette** [comment]
Log from `apt-get update` : 
```
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                      
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                               
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                               
Ign:6 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:7 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Get:8 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [819 B]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [234 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [903 kB]
Err:8 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg      
  The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]        
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [735 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [56.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [539 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [245 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3492 B]
Fetched 3069 kB in 1s (1781 kB/s)   
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Release.gpg  The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
I have also tried the usual steps of deleting the `/var/lib/apt/lists` folder and updating again, as well as `apt-get clean`, the issue still remains.

**Comment by flx42** [comment]
@Pingmin @vincentbissonnette what's the output of `docker run --rm -ti nvidia/cuda:9.0-devel apt-key list`?

**Comment by vincentbissonnette** [comment]
Output: 
```
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/7FA2AF80 2016-06-24
uid                  cudatools <cudatools@nvidia.com>
```

**Comment by vincentbissonnette** [comment]
However, the issue appears to have been fixed, as I'm now unable to reproduce the error.
`apt-get update` now performs the update as usual: 
```
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]         
Ign:5 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [56.8 kB]                    
Get:8 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [539 kB]                                         
Ign:9 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Get:10 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]  
Get:11 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:12 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release [564 B]
Get:13 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [801 B]
Get:14 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release.gpg [801 B]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [245 kB]                            
Get:16 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3492 B]                
Get:17 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [109 kB]                  
Get:18 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [14.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [234 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [903 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [735 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5162 B]
Get:29 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7146 B]
Fetched 24.8 MB in 4s (5605 kB/s)                           
Reading package lists... Done
```
Any idea on what causes this issue ?

**Comment by flx42** [comment]
I'm not sure, our CDN can get into a bad state sometimes, it's difficult to debug since it seems to be region specific.
Please file a new issue if it happens again.

**Comment by Pingmin** [comment]
@flx42  Sorry, I just see these messages right now. I seems like it's OK now and I have updated CUDA to v9.1.85-1 for some days.

**Comment by riless** [comment]
I have the same Issue with `nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04`

```
Get:18 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [17.9 kB]
Err:18 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages
  Hash Sum mismatch
```

**Comment by flx42** [comment]
I've circulated the information internally, since I don't maintain this package repository.

**Comment by riless** [comment]
I've retried today, and now it works.

**Comment by classicsong** [comment]
I have the same problem these days:
`E: GPG error: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64  Release: The following signatures were invalid: NODATA 1  NODATA 2`

**Comment by flx42** [comment]
@classicsong try setting the repository as `https` and check if it changes something.
You will need the `apt-transport-https` package.

**Comment by jageshmaharjan** [comment]
I think it's a region-specific error, some region doesn't allow access on 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64'
The above link will redirect to this link "http://114.80.80.238:8089/ceshi/index.html". The content is in the Chinese language the translated version is:

```
Tips: The site is temporarily inaccessible

According to the relevant laws and regulations of the Ministry of Industry and Information, because your website has not yet been filed, the website cannot be accessed.

According to the Order No. 33 of the Ministry of Industry and Information Technology of the People's Republic of China: Websites that do not have record numbers cannot be solved
Analysis and opening, otherwise it is necessary to bear the relevant legal responsibility.
        	 
Please be sure that all enterprises and institutions must complete the record and open the website. Thank you for your support!
	
Century Connect Record Consultation Contact Information

Registration Advisory Telephone: 021-36359595
```

**Comment by peterborkuti** [comment]
What helped in my case:
0) install apt-transport-https
1) Setting link from to http: to https: in /etc/apt/sources.list.d/cuda.list
2) updating apt-key with the 
```
wget -qO - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub | sudo apt-key add -
```

**Comment by goodloop** [comment]
Thanks @peterborkuti. Step 1 really helped me.

**Comment by reubenjohn** [comment]
@peterborkuti Needed to perform an additional Step 3: `sudo apt clean` before `sudo apt update` worked to fix "`problems were found: Metadata files have errors`".

**Comment by htgeis** [comment]
It happened again. I have try the way mentioned above but it all failed. The same image worked in yesterday.

**Comment by shridharkini** [comment]
nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 has the same issues still.

**Comment by nuzhet** [comment]
I am getting this error today. It was working fine yesterday:

E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch

**Comment by khurramHazen** [comment]
same issue as @nuzhet

**Comment by flx42** [comment]
@nuzhet I can reproduce, I'm filing an issue internally.

**Comment by khurramHazen** [comment]
@flx42 Do you think using *9.1-cudnn7-devel-ubuntu16.04* will help?

**Comment by gpascualg** [comment]
I can also reproduce with `nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04` and `nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04`

**Comment by marcoaleixo** [comment]
I'm also having this error using this Dockerfile - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/nvidia-jupyter.Dockerfile

I'm from Brazil.

**Comment by pzawistowski** [comment]
Same situation from Poland.

**Comment by mgolub2** [comment]
Same issue in USA NW

**Comment by rpengms** [comment]
+1.

**Comment by mfojtak** [comment]
Same problem when building docker image.
```
Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
```

**Comment by flx42** [comment]
Yeah, I agree there is an issue, but I don't control this repository. I'm pushing for a resolution.
In the meantime, if your driver is recent enough (driver 410), you can use the CUDA 10.0 image on ubuntu 18.04: `nvidia/cuda:10.0-base-ubuntu18.04`
The 18.04 repository is not affected.

**Comment by mirekphd** [comment]
@flx42 It's gone, seems to be resolved.

**Comment by khurramHazen** [comment]
It is resolved in **nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04** too.

**Comment by flx42** [comment]
Cool! Thanks for confirming (and reporting!).
