### ISSUE TITLE
GPU isolation problem

### ISSUE THREAD

**Issue by echan00** [NVIDIA/nvidia-docker#905]
I am following the [instructions on this page](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation-(version-1.0)) to specify a single GPU in my docker and am not having any luck. It seems like all 6 GPUs are always being used.

Attempt 1:
```
docker run --runtime=nvidia -p 8500:8500 \
  --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 \
  --mount type=bind,source=/home/eee/T2T_Model/t2t_train/translate_enzh_wmt32k/transformer-transformer_base/export/,target=/models/my_model \
  --mount type=bind,source=/home/eee/T2T_Model/batching.conf,target=/models/batching.conf \
  -e MODEL_NAME=my_model -t tensorflow/serving:latest-gpu --batching_parameters_file=/models/batching.conf --enable_batching
```

Attempt 2:
```
NV_GPU=0 docker run --runtime=nvidia -p 8500:8500 \
  --mount type=bind,source=/home/eee/T2T_Model/t2t_train/translate_enzh_wmt32k/transformer-transformer_base/export/,target=/models/my_model \
  --mount type=bind,source=/home/eee/T2T_Model/batching.conf,target=/models/batching.conf \
  -e MODEL_NAME=my_model -t tensorflow/serving:latest-gpu --batching_parameters_file=/models/batching.conf --enable_batching

```

**Comment by echan00** [comment]
Perhaps the documentation is outdated? 

I solved with this command:
```
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 -p 8500:8500 \
  --mount type=bind,source=/home/eee/T2T_Model/t2t_train/translate_enzh_wmt32k/transformer-transformer_base/export/,target=/models/my_model \
  --mount type=bind,source=/home/eee/T2T_Model/batching.conf,target=/models/batching.conf \
  -e MODEL_NAME=my_model -t tensorflow/serving:latest-gpu --batching_parameters_file=/models/batching.conf --enable_batching

```

**Comment by RenaudWasTaken** [comment]
Hello!

You used the documentation for the version 1 which is intended for people who still have that version installed.
