### ISSUE TITLE
Error: Package: nvidia-docker2-2.0.3-1.docker18.09.2.noarch (nvidia-docker) 

### ISSUE THREAD

**Issue by tzyll** [NVIDIA/nvidia-docker#916]
I use docker the latest version:
docker-ce.x86_64            3:18.09.2-3.el7                    docker-ce-stable
while nvidia-docker2 requires: docker = 2:18.09.2

details//
Error: Package: nvidia-docker2-2.0.3-1.docker18.09.2.noarch (nvidia-docker)
           Requires: docker = 2:18.09.2
           Available: 2:docker-1.13.1-75.git8633870.el7.centos.x86_64 (extras)
               docker = 2:1.13.1-75.git8633870.el7.centos
           Available: 2:docker-1.13.1-84.git07f3374.el7.centos.x86_64 (extras)
               docker = 2:1.13.1-84.git07f3374.el7.centos
           Available: 2:docker-1.13.1-88.git07f3374.el7.centos.x86_64 (extras)
               docker = 2:1.13.1-88.git07f3374.el7.centos

**Comment by 928234269** [comment]
I also encountered the same problem

**Comment by yonisim** [comment]
we have also encountered that
downgrading to 18.09.1 until a fix will be released

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry about that, we released a fix yesterday.

**Comment by zerog2k** [comment]
How to get the fix?
Still seeing this error from centos7 and the repo:

```
Error: Package: nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch (nvidia-docker)
           Requires: docker-ce = 3:18.09.2
           Installed: 3:docker-ce-18.09.3-3.el7.x86_64 (@docker-ce-stable)
               docker-ce = 3:18.09.3-3.el7
```
repo file:
`https://nvidia.github.io/nvidia-docker/centos7/nvidia-docker.repo`
when installing nvidia-docker2

**Comment by RenaudWasTaken** [comment]
@zerog2k we updated the packages.

**Comment by soul0517** [comment]
@RenaudWasTaken 
Sorry, I cannot find the updated version that you mentioned before.
The docker version we are using is docker-ce-18.06.2.ce-3.
![wrapper](https://user-images.githubusercontent.com/1813609/55555487-f05cf900-5717-11e9-9aaa-d166559f6be9.png)
